name: proyecto
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_form_builder: ^9.5.0
  flutter_settings_ui: ^3.0.1
  panara_dialogs: ^0.1.5
  persistent_bottom_nav_bar: ^6.2.1
  provider: ^6.1.2
  shared_preferences: ^2.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
